name: "Dependabot Auto Approve"
# pull_request_target means that this will run on pull requests, but in the context of the base repo.
# This should mean PRs from dependabot are supported.
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    if: github.repository == 'velero-io/velero' && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve Dependabot PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
