name: Pull Request Changelog Check
# by setting `on: [pull_request]`, that means action will be trigger when PR is opened, synchronize, reopened.
# Add labeled and unlabeled events too.
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:

  build:
    if: github.repository == 'velero-io/velero'
    name: Run Changelog Check
    runs-on: ubuntu-latest
    steps:

    - name: Check out the code
      uses: actions/checkout@v7

    - name: Changelog check
      env:
        GH_TOKEN: ${{ github.token }}
      run: ./hack/changelog-check.sh
